### ISSUE TITLE
Home Assistant Component: Logger Warning

### ISSUE THREAD

**Issue by rakaandro** [gluap/pyduofern#14]
There is a new logger warning with 0.109:

2020-04-30 11:58:57 WARNING (MainThread) [homeassistant.helpers.translation] duofern: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this 

Solution:
rename
`pyduofern/examples/homeassistant/custom_components/duofern/.translations/`
to
`pyduofern/examples/homeassistant/custom_components/duofern/translations/`

**Comment by gluap** [comment]
Hi @rakaandro, thank you for reporting this, also for including the fix in your report. It should be fixed along with some more deprecation warnings in the most recent commit.

Cheers,
Paul

**Comment by rakaandro** [comment]
Now it is working fine - no warning anymore. Thanks

=============================================



WINSCP makes the trouble. After a full new reboot and restart WINSCP, new checkout of the repo it is working now.

Hi,
I have change my files in /config/custom_components/duofern to the new version.
After a full reboot, I still have the logger warning:

```
2020-05-22 19:18:19 WARNING (MainThread) [homeassistant.components.cover] CoverDevice is deprecated, modify DuofernShutter to extend CoverEntity
2020-05-22 19:18:19 WARNING (MainThread) [homeassistant.components.light] Light is deprecated, modify DuofernLight to extend LightEntity
```
Do I have to clean a cache somewhere? I checked the code, the new version is with `CoverEntity`

What can I do?

**Comment by gluap** [comment]
@rakaandro Thank you for reporting back and especially for also reporting that you found the issue. I'll close this then.
